# Task1 - Numpy

In [1]:
import numpy as np
 

In [2]:
a = np.array([
[1, 6],
[2, 8],
[2, 11],
[3, 10],    
[1, 7]
], dtype=float)



In [3]:
mean_a=np.array([0,0])
for i in range(0,np.shape(a)[0]):
    mean_a[0] += a[i,0]
    mean_a[1] += a[i,1]

In [4]:
k = (1.0  / float(np.shape(a)[0]))

In [5]:
mean_a = mean_a * k

In [6]:
a_centered = a - mean_a

In [7]:
a_centered

array([[-0.8, -2.4],
       [ 0.2, -0.4],
       [ 0.2,  2.6],
       [ 1.2,  1.6],
       [-0.8, -1.4]])

In [8]:
mean_a

array([1.8, 8.4])

In [9]:
a[:,0:1]

array([[1.],
       [2.],
       [2.],
       [3.],
       [1.]])

In [10]:
a[:,1:2]

array([[ 6.],
       [ 8.],
       [11.],
       [10.],
       [ 7.]])

# Task 2

In [11]:
a_centered_col0 = np.zeros((np.shape(a)[0]), dtype=float )
a_centered_col1 = np.zeros((np.shape(a)[0]), dtype=float )
for i in range(0,np.shape(a)[0]):
    a_centered_col0[i] = a_centered[i,0]
    a_centered_col1[i] = a_centered[i,1]
    
  
    

In [12]:
a_centered_col0

array([-0.8,  0.2,  0.2,  1.2, -0.8])

# Task 3

In [13]:
a_centered_sp  = np.dot(a_centered_col0,a_centered_col1)
print(a_centered_sp )

5.3999999999999995


In [14]:
p = np.shape(a)[0]-1
a_cov = a_centered_sp / p

 

In [15]:
print("method1: covariation = ",a_cov)

method1: covariation =  1.3499999999999999


# Task 4

In [16]:
a_cov2_m = np.cov(a.T)
print(a_cov2_m)

[[0.7  1.35]
 [1.35 4.3 ]]


In [17]:
a_cov2 = a_cov2_m[0,1]
print("method2: covariation = ",a_cov2)

method2: covariation =  1.3499999999999999
