# Lesson 6 - task 2

## Task 1 code - to compare with forthcoming data of Task 2

In [1]:

import numpy as np
import pandas as pd

from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

%matplotlib inline
%config InlineBackend.figure_format = 'svg'



In [2]:

boston = load_boston()


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (

In [3]:
# boston

In [4]:
# boston.keys()

In [5]:
data = boston.data

target = boston.target

In [6]:
# data

In [7]:
feature_names = boston.feature_names

In [8]:
X = pd.DataFrame(data, columns=feature_names)

In [9]:
y = pd.DataFrame(target, columns = ['price'] )

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [11]:
X_test

CRIM    ZN  INDUS  CHAS    NOX     RM    AGE     DIS   RAD    TAX  \
173  0.09178   0.0   4.05   0.0  0.510  6.416   84.1  2.6463   5.0  296.0   
274  0.05644  40.0   6.41   1.0  0.447  6.758   32.9  4.0776   4.0  254.0   
491  0.10574   0.0  27.74   0.0  0.609  5.983   98.8  1.8681   4.0  711.0   
72   0.09164   0.0  10.81   0.0  0.413  6.065    7.8  5.2873   4.0  305.0   
452  5.09017   0.0  18.10   0.0  0.713  6.297   91.8  2.3682  24.0  666.0   
..       ...   ...    ...   ...    ...    ...    ...     ...   ...    ...   
441  9.72418   0.0  18.10   0.0  0.740  6.406   97.2  2.0651  24.0  666.0   
23   0.98843   0.0   8.14   0.0  0.538  5.813  100.0  4.0952   4.0  307.0   
225  0.52693   0.0   6.20   0.0  0.504  8.725   83.0  2.8944   8.0  307.0   
433  5.58107   0.0  18.10   0.0  0.713  6.436   87.9  2.3158  24.0  666.0   
447  9.92485   0.0  18.10   0.0  0.740  6.251   96.6  2.1980  24.0  666.0   

     PTRATIO       B  LSTAT  
173     16.6  395.50   9.04  
274     17.6  396.90   3.53  
491     20.1  390.11  18.07  
72      19.2  390.91   5.52  
452     20.2  385.09  17.27  
..       ...     ...    ...  
441     20.2  385.96  19.52  
23      21.0  394.54  19.88  
225     17.4  382.00   4.63  
433     20.2  100.19  16.22  
447     20.2  388.52  16.44  

[152 rows x 13 columns]

In [12]:
from sklearn.linear_model import LinearRegression

In [13]:
#lr

In [14]:
#lr.fit( X_train, y_train)

In [15]:
import numpy as np
from sklearn.linear_model import LinearRegression
X = np.array([[1, 1], [1, 2], [2, 2], [2, 3]])
# y = 1 * x_0 + 2 * x_1 + 3
y = np.dot(X, np.array([1, 2])) + 3
reg = LinearRegression().fit(X, y)
reg.score(X, y)

lr = LinearRegression().fit( X_train, y_train)
lr

LinearRegression()

In [16]:
y_pred = lr.predict(X_test)

In [17]:
# y_pred

In [18]:
check_test = pd.DataFrame({'y_test': y_test['price'], 
                           'y_pred': y_pred.flatten() },
                         columns=['y_test','y_pred'])

In [19]:
# check_test.head(10)

In [20]:
from sklearn.metrics import r2_score

r2_lin = r2_score(y_test, y_pred)
r2_lin

0.7112260057484878

# Task 2

## Importing class

In [21]:
from sklearn.ensemble import RandomForestRegressor 

## Creating RandomForestRegressor model

In [22]:
model  = RandomForestRegressor(n_estimators =1000, max_features = 12, random_state = 42 )


In [23]:
y_train.values[:, 0]


array([28.7, 21.2, 19.3, 23.1, 19.1, 25. , 33.4,  5. , 29.6, 18.7, 21.7,
       23.1, 22.8, 21. , 48.8, 14.6, 16.6, 27.1, 20.1, 19.8, 21. , 41.3,
       23.2, 20.4, 18.5, 29.4, 36.4, 24.4, 11.8, 13.8, 12.3, 17.8, 33.1,
       26.7, 13.4, 14.4, 50. , 22. , 19.9, 23.8, 17.5, 12.7,  5.6, 31.1,
       26.2, 19.4, 16.7, 13.8, 22.9, 15.3, 27.5, 36.1, 22.9, 24.5, 25. ,
       50. , 34.9, 31.7, 24.1, 22.1, 14.1, 42.8, 19.3, 32.2, 26.4, 21.8,
       21.7,  8.3, 46.7, 43.1, 31.5, 10.5, 16.7, 20. , 33.3, 17.8, 50. ,
       20.5, 23.2, 13.1, 19.6, 22.8, 28.7, 30.7, 22.9, 21.9, 23.9, 32.7,
       24.3, 21.5, 24.6,  8.5, 26.4, 23.1, 15. ,  8.8, 19.3, 23.9, 24.7,
       19.8, 23.8, 13.3, 29. , 27.1, 34.6, 13.3, 15.6, 12.5, 14.6, 11. ,
       24.8, 17.3,  8.1, 21.4, 15.6, 23.3, 32. , 38.7, 30.1, 20.5, 32.5,
       42.3, 24.3, 20.6, 22. , 18.2, 15. ,  6.3, 20.1, 21.4, 28.4, 30.1,
       20.8, 23. , 14.3, 11.7, 37.3, 17.1, 10.4, 23. , 22.7, 20.3, 21.7,
       50. ,  8.4, 18.8, 37.2, 16.1, 16.5, 22.2, 20

## Training model

In [24]:
model.fit(X_train, y_train.values[:, 0])

RandomForestRegressor(max_features=12, n_estimators=1000, random_state=42)

## Predicting on test data

In [25]:
y_pred2 = model.predict(X_test)

In [26]:
y_pred2

array([22.8199, 31.2164, 16.2683, 23.9376, 17.1455, 21.6991, 19.8384,
       14.8237, 21.2323, 20.9064, 20.1005, 19.867 ,  8.0011, 21.5494,
       19.2877, 25.2796, 18.7811,  8.5068, 45.6868, 15.6068, 24.4109,
       24.0333, 14.5752, 23.4224, 15.0554, 15.3808, 21.6604, 13.9595,
       19.6921, 21.0655, 19.8107, 23.3132, 29.0913, 20.2658, 14.407 ,
       16.0116, 34.6151, 19.0304, 21.1547, 24.2885, 18.5613, 29.4533,
       45.4153, 19.6345, 22.6448, 14.0905, 15.8194, 24.5395, 19.0633,
       28.0541, 21.4537, 33.9004, 17.6524, 26.2458, 45.5511, 22.0171,
       15.9844, 32.4567, 22.1402, 20.4842, 25.3627, 33.5781, 30.3512,
       18.9443, 27.092 , 17.1117, 13.9436, 23.1884, 28.7462, 15.5616,
       20.6118, 28.3794, 10.3808, 22.1311, 22.2591,  6.9513, 19.9867,
       46.014 , 11.0742, 12.4401, 21.7946, 11.7881, 19.9995,  9.3018,
       20.5308, 26.8788, 15.9973, 23.2604, 23.7897, 17.8234, 21.889 ,
        7.2897, 19.8827, 19.2217, 23.632 , 19.8371, 37.8678, 11.7291,
       12.5307, 12.4

## Assessing model

In [27]:
r2_tree = r2_score(y_test, y_pred2)
r2_tree

0.876228022524578

In [28]:
r2_tree == r2_lin

False

In [29]:
y_pred[0]

array([28.64896005])

In [30]:
y_pred2[0]

22.819899999999905

## Comparing RandomForestRegressor and LinearRegression prediction quality

In [31]:
if r2_tree == r2_lin:
    print("RandomForestRegressor and LinearRegression work equally well")
elif r2_tree > r2_lin:
    print("RandomForestRegressor works better than LinearRegression")
else:
    print("LinearRegression works better than RandomForestRegressor")

    

RandomForestRegressor works better than LinearRegression
