# Lesson 6 - Task 3

## Earlier Tasks 1 and 2 code to use in consequent Task 3 calculations

In [1]:

import numpy as np
import pandas as pd

from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

%matplotlib inline
%config InlineBackend.figure_format = 'svg'



In [2]:

boston = load_boston()


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (

In [3]:
# boston

In [4]:
# boston.keys()

In [5]:
data = boston.data

target = boston.target

In [6]:
# data

In [7]:
feature_names = boston.feature_names

In [8]:
X = pd.DataFrame(data, columns=feature_names)

In [9]:
y = pd.DataFrame(target, columns = ['price'] )

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [11]:
# X_test

In [12]:
from sklearn.linear_model import LinearRegression

In [13]:
import numpy as np
from sklearn.linear_model import LinearRegression
X = np.array([[1, 1], [1, 2], [2, 2], [2, 3]])
# y = 1 * x_0 + 2 * x_1 + 3
y = np.dot(X, np.array([1, 2])) + 3
reg = LinearRegression().fit(X, y)
reg.score(X, y)

lr = LinearRegression().fit( X_train, y_train)
lr

LinearRegression()

In [14]:
y_pred = lr.predict(X_test)

In [15]:
# y_pred

In [16]:
check_test = pd.DataFrame({'y_test': y_test['price'], 
                           'y_pred': y_pred.flatten() },
                         columns=['y_test','y_pred'])

In [17]:
#check_test.head(10)

In [18]:
from sklearn.metrics import r2_score

r2_lin = r2_score(y_test, y_pred)
r2_lin

0.7112260057484878

In [19]:
#task 2

In [20]:
from sklearn.ensemble import RandomForestRegressor 

In [21]:
model  = RandomForestRegressor(n_estimators =1000, max_features = 12, random_state = 42 )


In [22]:
# y_train.values[:, 0]


In [23]:
model.fit(X_train, y_train.values[:, 0])

RandomForestRegressor(max_features=12, n_estimators=1000, random_state=42)

In [24]:
y_pred2 = model.predict(X_test)

In [25]:
# y_pred2

In [26]:
r2_tree = r2_score(y_test, y_pred2)
r2_tree

0.876228022524578

In [27]:
r2_tree == r2_lin

False

In [28]:
y_pred[0]

array([28.64896005])

In [29]:
y_pred2[0]

22.819899999999905

In [30]:
if r2_tree == r2_lin:
    print("RandomForestRegressor and LinearRegression work equally well")
elif r2_tree > r2_lin:
    print("RandomForestRegressor works better than LinearRegression")
else:
    print("LinearRegression works better than RandomForestRegressor")

    

RandomForestRegressor works better than LinearRegression


# Task 3

## Feature Importances and names output

In [31]:
model.feature_importances_

array([0.03320554, 0.0016986 , 0.0073623 , 0.00124517, 0.01811565,
       0.39549044, 0.01532505, 0.06339276, 0.00516123, 0.0124675 ,
       0.01884221, 0.01245306, 0.41524049])

In [32]:
model.feature_names_in_

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype=object)

## Calculating the sum of feature importances and finding 2 highest values

In [33]:
sum = 0
imax = 0
imax2 = 0
imin = 0

# sum of factors and minimum
for i in range(0,len(model.feature_importances_)):    
    sum += model.feature_importances_[i]
    if model.feature_importances_[i]<model.feature_importances_[imin]:
        imin = i
        
imax = imin
imax2 = imin

# 1st and 2nd most significant features
for i in range(0,len(model.feature_importances_)):    
    if model.feature_importances_[i]>model.feature_importances_[imax]:
        imax2 = imax
        imax = i
        
print( "sum of feature factors is %f" % (sum) )  

sum of feature factors is 1.000000


In [34]:
imax

12

In [35]:
imax2

5

## The most significant feature

In [36]:
print( "The 1st most significant feature with index = %d is '%s' = %f" % (imax, model.feature_names_in_[imax] , model.feature_importances_[imax]) )


The 1st most significant feature with index = 12 is 'LSTAT' = 0.415240


# The second most significant feature

In [37]:
print( "The 2nd most significant feature with index = %d is '%s' = %f" % (imax2, model.feature_names_in_[imax2] , model.feature_importances_[imax2]) )

The 2nd most significant feature with index = 5 is 'RM' = 0.395490


## Sorting array of feature values

In [38]:
imp_copy = model.feature_importances_[:]
imp_copy

array([0.03320554, 0.0016986 , 0.0073623 , 0.00124517, 0.01811565,
       0.39549044, 0.01532505, 0.06339276, 0.00516123, 0.0124675 ,
       0.01884221, 0.01245306, 0.41524049])

In [39]:
 
imp_copy = sorted(imp_copy, reverse=1)

In [40]:
imp_copy

[0.4152404896167567,
 0.39549043883372675,
 0.06339276450950124,
 0.033205540865315304,
 0.018842213486265375,
 0.018115650533400928,
 0.015325046453109845,
 0.012467502971042222,
 0.012453055836697662,
 0.00736230094389105,
 0.005161232038500045,
 0.001698595223626342,
 0.0012451686881666047]